### ISSUE TITLE
java.lang.SecurityException

### ISSUE THREAD

**Issue by alexwan02** [Coolerfall/Android-AppDaemon#11]
部分手机会有SecurityException的异常信息

``` java
Message: 
    Unable to create application com.skysea.skysay.base.BaseApp: java.lang.SecurityException: 
    Unable to start service Intent { cmp=com.skysea.skysay/.service.DaemonService }: Unable to launch app com.skysea.skysay/10101 for service Intent { cmp=com.skysea.skysay/.service.DaemonService }: user 0 is restricted
```

具体栈信息

``` java
Tue Mar 29 06:37:00 GMT+08:00 2016

Thread: 1

Message: Unable to create application com.skysea.skysay.base.BaseApp: java.lang.SecurityException: Unable to start service Intent { cmp=com.skysea.skysay/.service.DaemonService }: Unable to launch app com.skysea.skysay/10101 for service Intent { cmp=com.skysea.skysay/.service.DaemonService }: user 0 is restricted

Manufacturer: OPPO
Model: OPPO R7sm
Product: R7sm

Android Version: 5.1.1
API Level: 22
Heap Size: 256MB

Version Code: 29
Version Name: 2.9

Mac Address : dc6dcd914c46

Stack Trace:

java.lang.RuntimeException: Unable to create application com.skysea.skysay.base.BaseApp: java.lang.SecurityException: Unable to start service Intent { cmp=com.skysea.skysay/.service.DaemonService }: Unable to launch app com.skysea.skysay/10101 for service Intent { cmp=com.skysea.skysay/.service.DaemonService }: user 0 is restricted
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4783)
    at android.app.ActivityThread.access$1700(ActivityThread.java:164)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:159)
    at android.app.ActivityThread.main(ActivityThread.java:5541)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by: java.lang.SecurityException: Unable to start service Intent { cmp=com.skysea.skysay/.service.DaemonService }: Unable to launch app com.skysea.skysay/10101 for service Intent { cmp=com.skysea.skysay/.service.DaemonService }: user 0 is restricted
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1769)
    at android.app.ContextImpl.startService(ContextImpl.java:1742)
    at android.content.ContextWrapper.startService(ContextWrapper.java:527)
    at com.skysea.skysay.base.BaseApp.onCreate(SourceFile:104)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4780)
    ... 9 more

```

**Comment by coolerfall** [comment]
什么情况下报错的

**Comment by alexwan02** [comment]
@Coolerfall 只有在 OPPO R系列上会有这个问题，并且不是一定出现的问题。
[OPPO R7](http://bbs.coloros.com/thread-171731-1-1.html)
[Service在OPPO系列手机下无法启动](http://bbs.coloros.com/find7-174655-1-1.html)
oppo bbs上也有相关的问题。他们给出的解释是：`OPPO手机内置有耗电管理的功能，可能该应用服务在后台启动时被判断为耗电的一种操作行为`；

**Comment by coolerfall** [comment]
这个就没法控制了
